version: '3'

services:
  code-server:
    build: .
    container_name: code-server-local
    ports: 
      - "8080:8080"
    volumes:
      - ./:/home/coder/mount
    command: "--cert /home/coder/cert.crt --cert-key /home/coder/cert.key"

# UID=${UID} GID=${GID} docker-compose up
